roulette/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from base import views

urlpatterns = [
    path('', views.Landing.as_view(), name="landing"),
    path('leaderboard/', views.Leaderboard.as_view(), name="leaderboard"),
    path('turn/<int:pk>', views.TurnBets.as_view(), name="turn"),
    path('place-bet/<int:pk>', views.PlaceBet.as_view(), name="place-bet"),
    path('manual/', views.Manual.as_view(), name="manual"),
    path('no-round/', views.NoRound.as_view(), name="no-round"),
    path('bettor/<int:pk>/placed-wagers/', views.PlacedWagers.as_view(), name="transactions"),

    path('accounts/login/', auth_views.LoginView.as_view(), name="login"),
    path('accounts/logout/', auth_views.LogoutView.as_view(), name="logout"),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

base/models.py
import math
from django.conf import settings
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models, transaction
from django.db.models import (
    Case,
    FloatField,
    F,
    Q,
    Sum,
    When
)
from django.db.models.signals import post_save


class Bet(models.Model):
    description = models.CharField(max_length=100)
    odds = models.FloatField()
    turn = models.ForeignKey('Turn', on_delete=models.CASCADE)
    did_happen = models.BooleanField(default=False)
    order = models.PositiveIntegerField(default=0, blank=False, null=False)

    def __str__(self):
        return '{} til odds {} i runde {}'.format(self.description, self.odds, self.turn)

    class Meta:
        ordering = ('turn', 'order',)


class Turn(models.Model):
    name = models.CharField(max_length=100)
    active = models.BooleanField(default=False)

    def __str__(self):
        return '{} (id: {})'.format(self.name, self.id)


class Transaction(models.Model):
    created = models.DateTimeField(auto_now_add=True, blank=True)
    bettor = models.ForeignKey('Bettor', on_delete=models.CASCADE)
    bet = models.ForeignKey('Bet', on_delete=models.CASCADE, null=True, blank=True)
    wager = models.PositiveIntegerField()

    @property
    def result(self):
        bet = getattr(self, "bet")
        if bet and not bet.turn.active:
            if bet.did_happen:
                return bet.odds * self.wager
            return self.wager * -1
        return None

    def clean(self):
        if self.bet:
            if not self.bet.turn.active:
                raise ValidationError({'bet': "Runden er ikke aktiv"})
            if self.wager > self.bettor.credits:
                raise ValidationError({'wager': "Du har ikke nok jetoner til at placere denne satsning"})
            if self.wager <= 0:
                raise ValidationError({'wager': "Nej"})

    def __str__(self):
        if not self.bet:
            return "{} Startjetoner : {}".format(
                self.bettor.user.username,
                self.wager,
            )
        return "{} satsede {} jetoner på {}. Runde: '{}'".format(
            self.bettor.user.username,
            self.wager,
            self.bet.description,
            self.bet.turn,
        )

    class Meta:
        ordering = ('-created',)


class BettorQuerySet(models.QuerySet):
    def with_credits(self):
        return self.annotate(
            annotated_credits=Sum(
                Case(
                    When(
                        Q(transaction__bet__isnull=False) &
                        Q(transaction__bet__did_happen=True),
                        then=F('transaction__wager') * F('transaction__bet__odds') - F('transaction__wager'),
                    ),
                    When(
                        Q(transaction__bet__isnull=False) &
                        Q(transaction__bet__did_happen=False),
                        then=-1 * F('transaction__wager'),
                    ),
                    When(
                        Q(transaction__bet__isnull=True),
                        then=F('transaction__wager'),
                    ),
                    output_field=FloatField()
                )
            )
        )


class BettorManager(models.Manager):
    def get_queryset(self):
        return BettorQuerySet(self.model, using=self._db).with_credits().order_by('-annotated_credits')


class Bettor(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    objects = BettorManager()

    @property
    def credits(self):
        return math.floor(Bettor.objects.filter(pk=self.pk).with_credits().first().annotated_credits)

    def __str__(self):
        return self.user.username


def create_bettor(sender, instance, created, **kwargs):
    if created:
        with transaction.atomic():
            bettor = Bettor(user=instance)
            bettor.save()
            Transaction(
                bettor=bettor,
                wager=settings.STARTING_CREDITS,
            ).save()


post_save.connect(create_bettor, sender=User)

base/views.py
from django.views.generic import (
    CreateView,
    DetailView,
    RedirectView,
    TemplateView
)
from django.core.exceptions import (
    MultipleObjectsReturned,
    ObjectDoesNotExist,
    SuspiciousOperation
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from base import models


class Landing(LoginRequiredMixin, RedirectView):
    def get_redirect_url(self):
        try:
            pk = models.Turn.objects.get(active=True).pk
            return reverse('turn', kwargs={'pk': pk})
        except (ObjectDoesNotExist, MultipleObjectsReturned):
            return "no-round"


class TurnBets(LoginRequiredMixin, DetailView):
    template_name = "turn.html"
    model = models.Turn


class PlaceBet(LoginRequiredMixin, CreateView):
    success_url = "/"
    model = models.Transaction
    fields = ('bettor', 'bet', 'wager')
    template_name = "place-bet.html"

    def dispatch(self, request, *args, **kwargs):
        self.bet = models.Bet.objects.get(pk=kwargs['pk'])
        if not self.bet.turn.active:
            raise SuspiciousOperation("Fuuuuck af")
        return super().dispatch(request, **kwargs)

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['bet'] = self.bet
        return context

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        if self.request.method == 'POST':
            data = {
                'wager': self.request.POST['wager'],
                'bettor': self.request.user.bettor.pk,
                'bet': self.bet.pk
            }
            kwargs['data'] = data
        return kwargs


class Leaderboard(LoginRequiredMixin, TemplateView):
    template_name = "leaderboard.html"

    def get_context_data(self):
        context = super().get_context_data()
        context['bettors'] = models.Bettor.objects.filter(user__is_active=True).select_related('user')
        return context


class PlacedWagers(LoginRequiredMixin, DetailView):
    template_name = "placed-wagers.html"
    model = models.Bettor

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset\
            .prefetch_related(
                "transaction_set",
                "transaction_set__bet",
                "transaction_set__bet__turn",
            )\
            .select_related('user')
        return queryset


class Manual(LoginRequiredMixin, TemplateView):
    template_name = "manual.html"


class NoRound(LoginRequiredMixin, TemplateView):
    template_name = "no_round.html"

anneogvidir/templates/base.html
{% load static %} {% load staticfiles %}
<!DOCTYPE html>
<html lang="en">

<head>
    {% load static %} {% load staticfiles %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js" integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn" crossorigin="anonymous"></script>
    <title>Babyrouletten</title>
    <style>
        body {
            font-size: 16px;
            line-height: 1.6em;
        }

        .round {
            text-align: center;
            margin-bottom: 60px;
        }

        a {
            color: rgb(59, 194, 186);
        }

        .btn-primary,
        .btn-primary:hover {
            background-color: rgb(59, 194, 186);
            border: none;
        }

        .credits {
            text-align: center;
            margin: 0 0 60px 0;
            font-size: 18px;
        }
        .betrow {
            margin: 10px;
        }

        h1 {
            margin-bottom: 60px;
            text-align: center;
        }

        body {
            background-color: #6b92b9;
        }
        .logo {
            max-height: 33vh;
            padding: 20px;
            margin: 0 auto;
        }

        .me a {
            color: black !important;
        }

        footer {
            height: 200px;
        }
    </style>
</head>

<body>
    {% block navbar %}
        <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="{% url "landing" %}">Babyrouletten</a>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url "landing" %}">Hjem</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'manual' %}">Manual</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'transactions' pk=user.bettor.pk %}">Mine væddemål</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'leaderboard' %}">Pointtavle</a>
                    </li>
                </ul>
                <div class="form-inline my-2 my-lg-0">
                    <a href="{% url 'transactions' pk=user.bettor.pk %}">{{ user }} // Resterende jetoner: {{ user.bettor.credits }}</a>
                </div>
            </div>
        </nav>
    {% endblock %}

    <div class="container">
        <div class="row">
        {% block logo %}
            <img class="logo img-fluid" src="{% static "logo.png" %}"  />
        {% endblock %}
        </div>
        {% block content %}{% endblock %}
    </div>
    <footer>

    </footer>
</body>

</html>

anneogvidir/templates/manual.html
{% extends "base.html" %}
{% block content %}
<h1>Manual til Babyrouletten</h1>
{% endblock %}

base/templates/leaderboard.html
{% extends "base.html" %} {% block content %}
<h1>Pointtavle</h1>
<table class="table table-striped">
    <tr>
        <td>Brugernavn</td>
        <td>Jetoner</td>
    </tr>
    {% for bettor in bettors %}
    <tr>
        <td>
            <a href="{% url 'transactions' pk=bettor.id %}">{{bettor.user}}</a>
        </td>
        <td>{{ bettor.annotated_credits|floatformat:1 }}</td>
    </tr>
    {% endfor %}
</table>
{% endblock %}

base/templates/place-bet.html
{% extends "base.html" %} {% block content %}
<h1>Sats jetoner på {{ bet.description }} til odds {{ bet.odds }}</h1>

    <form method="POST">
        {% csrf_token %}
        <div class="row">
            <input type="number" placeholder="Skriv din indsats her" name="wager" id="id_wager" required="" min=1 max={{ user.bettor.credits }} class="col-6" />
            <button type="submit" class="btn btn-primary col-6">Placér satsning</button>
        </div>
    </form>
    <h1>{{ form.errors.wager.0 }}</h1>
    <a href="{% url 'landing' %}" class="btn btn-secondary col-12">Gå tilbage</a>

</div>

{% endblock %}

base/templates/placed-wagers.html
{% extends "base.html" %}
{% block content %}
<h1>Væddemål for {{ object.user }}</h1>
<h2>{{ object.user }} har i alt <b>{{ object.credits|floatformat:1 }}</b> jetoner</h2>
<table class="table table-striped table-responsive">
  <tr>
    <td>Runde #</td>
    <td>Væddemål</td>
    <td>Odds</td>
    <td>Indsats</td>
    <td>Resultat</td>
  </tr>
{% for transaction in object.transaction_set.all %}
  <tr>
    {% if transaction.bet %}
      <td>{{ transaction.bet.turn.id }}</td>
      <td>{{ transaction.bet.description }}</td>
      <td>{{ transaction.bet.odds }}</td>
      <td>{{ transaction.wager }}</td>
      <td>
      {% with transaction.result as result %}
        {% if result %}
          {{ result|floatformat:1 }}
        {% else %}
          Afventer udfald
        {% endif %}
        {% endwith %}
      </td>
      {% else %}
          <td>-</td>
          <td>{{ transaction.wager }} startjetoner</td>
          <td>1,0</td>
          <td>{{ transaction.wager }}</td>
          <td/>{{ transaction.wager }}</td>
      {% endif %}
  </tr>
{% endfor %}
</table>
{% endblock %}

base/templates/turn.html
{% extends "base.html" %}
{% block content %}
<div class="main">
  <div class="row">
    <div class="col-12">
      <h1 class="round">{{ object.name }}</h1>
        {% if not object.active %}
          <h2>Denne runde er ikke længere aktiv</h2>
        {% endif %}
        <p class="credits">Du har <b>{{ user.bettor.credits }}</b> jetoner tilbage at spille for</p>
        <table class="table table-striped">
            <thead>
              <tr>
                <th>Væddemål</th>
                <th>Odds</th>
                <th>Sats</th>
              </tr>
            </thead>
            <tbody>
          {% for bet in object.bet_set.all %}
          <tr>
              <th>{{ bet.description }}</th>
              <th>{{ bet.odds }}</th>
              <th>{% if object.active %}<a class="btn btn-primary btn-block" href="{% url 'place-bet' pk=bet.pk %}">Sats</a>{% endif %}</th>
            </a>
          </tr>

          {% endfor %}
          </tbody>
        </table>
    </div>
  </div>
</div>
{% endblock %}

marcus/templates/no_round.html
{% extends "base.html" %}
{% block content %}
<h1>Runden er lukket, nu venter vi på barnet</h1>
{% endblock %}